# Generated by Django 4.2.2 on 2023-07-02 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_demostreamblock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoStreamBlock',
        ),
    ]
