# Generated by Django 4.2.2 on 2023-07-02 03:49

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_indicadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='corp',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mary',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.DeleteModel(
            name='Indicadores',
        ),
    ]
