# Generated by Django 4.2.2 on 2023-07-06 16:53

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_flexpage_alter_homepage_mary'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='zelda',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
