# Generated by Django 4.2.2 on 2023-07-06 20:25

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_zelda'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='flexpage',
            name='subtitle',
            field=wagtail.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
    ]
