# Generated by Django 4.2.1 on 2023-07-18 00:59

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_secondpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='home_link',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
