# Generated by Django 4.2.1 on 2023-07-18 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_flexpage_home_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flexpage',
            name='home_link',
        ),
    ]
