# Generated by Django 4.2.1 on 2023-07-18 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0013_remove_flexpage_home_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlexPage',
            new_name='Indicador',
        ),
        migrations.RenameModel(
            old_name='SecondPage',
            new_name='Informes',
        ),
    ]
