# Generated by Django 4.2.1 on 2023-07-18 02:57

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_pmo'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='corp',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
