# Generated by Django 4.2.1 on 2023-07-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0017_indicadordetalles_indicadorformulario_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indicador',
            new_name='Login',
        ),
    ]
