# Generated by Django 4.2.1 on 2023-07-27 16:16

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0020_demostreamblock_delete_parametroindicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroIndicador',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('codigo', wagtail.fields.RichTextField()),
                ('atributo', wagtail.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='DemoStreamBlock',
        ),
    ]
