# Generated by Django 4.2.1 on 2023-08-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0021_parametroindicador_delete_demostreamblock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndicadorDetalles',
            new_name='Indicador',
        ),
    ]
