# Generated by Django 4.1.10 on 2023-08-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_indicadordetalles_indicador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicadorgrafico',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='indicadorparametros',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='IndicadorFormulario',
        ),
        migrations.DeleteModel(
            name='IndicadorGrafico',
        ),
        migrations.DeleteModel(
            name='IndicadorParametros',
        ),
    ]
