# Generated by Django 4.1.10 on 2023-08-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_indicadorgrafico_page_ptr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParametroIndicador',
        ),
    ]
