# Generated by Django 4.1.10 on 2023-08-20 17:18

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0024_delete_parametroindicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoInforme',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.CharField(default='', max_length=140)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('mary', wagtail.fields.RichTextField(blank=True)),
                ('corp', wagtail.fields.RichTextField(blank=True)),
                ('zelda', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
