# Generated by Django 4.1.10 on 2023-08-20 17:40

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_nuevoinforme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuevoinforme',
            name='corp',
        ),
        migrations.RemoveField(
            model_name='nuevoinforme',
            name='mary',
        ),
        migrations.RemoveField(
            model_name='nuevoinforme',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='nuevoinforme',
            name='zelda',
        ),
        migrations.AlterField(
            model_name='nuevoinforme',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock())], use_json_field=True),
        ),
    ]
