# Generated by Django 4.1.10 on 2023-08-20 17:48

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_nuevoinforme_corp_remove_nuevoinforme_mary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nuevoinforme',
            old_name='body',
            new_name='parametros',
        ),
        migrations.AddField(
            model_name='nuevoinforme',
            name='comentario',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='nuevoinforme',
            name='estado',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='nuevoinforme',
            name='id_indicador',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='nuevoinforme',
            name='medida',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='nuevoinforme',
            name='responsable',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='nuevoinforme',
            name='tema_material',
            field=models.CharField(default='', max_length=140),
        ),
    ]
