# Generated by Django 4.1.10 on 2023-08-20 17:54

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_rename_body_nuevoinforme_parametros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevoinforme',
            name='parametros',
            field=wagtail.fields.StreamField([('nombre', wagtail.blocks.RichTextBlock()), ('valor', wagtail.blocks.RichTextBlock())], use_json_field=True),
        ),
    ]
