# Generated by Django 4.1.10 on 2023-08-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_nuevoinforme_parametros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuevoinforme',
            name='parametros',
        ),
    ]
