# Generated by Django 4.1.10 on 2023-08-21 15:54

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_nuevoinforme_parametros'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevoinforme',
            name='tipo',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='nuevoinforme',
            name='estado',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='nuevoinforme',
            name='id_indicador',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='nuevoinforme',
            name='medida',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='nuevoinforme',
            name='responsable',
            field=wagtail.fields.RichTextField(),
        ),
    ]
