# Generated by Django 4.1.10 on 2023-08-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_rename_indicador_indicadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevoinforme',
            name='comentario',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='nuevoinforme',
            name='estado',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='nuevoinforme',
            name='id_indicador',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='nuevoinforme',
            name='medida',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='nuevoinforme',
            name='responsable',
            field=models.CharField(max_length=140),
        ),
    ]
