# Generated by Django 4.1.10 on 2023-08-22 20:58

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_nuevoinforme_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevoinforme',
            name='parametros',
            field=wagtail.fields.StreamField([('nombre', wagtail.blocks.RichTextBlock()), ('valor', wagtail.blocks.RichTextBlock()), ('tipo', wagtail.blocks.RichTextBlock())], default=1, use_json_field=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nuevoinforme',
            name='comentario',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
