# Generated by Django 4.1.10 on 2023-08-22 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_nuevoinforme_parametros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuevoinforme',
            name='parametros',
        ),
    ]
