# Generated by Django 4.1.10 on 2023-08-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_nuevoinforme_parametros'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevoinforme',
            name='tipo',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
