# Generated by Django 4.1.10 on 2023-08-25 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_postpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostPage',
        ),
    ]
