# Generated by Django 4.1.10 on 2023-08-26 18:23

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0039_delete_postpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestInforme',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tema_material', models.CharField(default='', max_length=140)),
                ('id_indicador', models.CharField(max_length=140)),
                ('medida', models.CharField(max_length=140)),
                ('responsable', models.CharField(max_length=140)),
                ('comentario', models.CharField(blank=True, max_length=500)),
                ('estado', models.CharField(max_length=140)),
                ('categoria', models.CharField(max_length=140)),
                ('parametros', wagtail.fields.StreamField([('nombre', wagtail.blocks.RichTextBlock()), ('valor', wagtail.blocks.RichTextBlock()), ('tipo', wagtail.blocks.RichTextBlock())], use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
