# Generated by Django 4.1.10 on 2023-08-27 20:42

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_anothertestinforme_alter_testinforme_parametros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anothertestinforme',
            name='parametros',
            field=wagtail.fields.StreamField([('bloque', wagtail.blocks.StructBlock([('year', wagtail.blocks.CharBlock()), ('material', wagtail.blocks.CharBlock()), ('valor', wagtail.blocks.CharBlock()), ('porcentaje', wagtail.blocks.CharBlock())]))], use_json_field=True),
        ),
    ]
