# Generated by Django 4.1.10 on 2023-08-27 20:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_anothertestinforme_parametros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anothertestinforme',
            name='parametros',
        ),
        migrations.AddField(
            model_name='anothertestinforme',
            name='buroku',
            field=wagtail.fields.StreamField([('paramentros', wagtail.blocks.StructBlock([('year', wagtail.blocks.CharBlock()), ('material', wagtail.blocks.CharBlock()), ('valor', wagtail.blocks.CharBlock()), ('porcentaje', wagtail.blocks.CharBlock())]))], default=1, use_json_field=True),
            preserve_default=False,
        ),
    ]
