# Generated by Django 4.1.10 on 2023-08-27 21:05

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_remove_anothertestinforme_parametros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anothertestinforme',
            name='buroku',
            field=wagtail.fields.StreamField([('paramentros', wagtail.blocks.StructBlock([('year', wagtail.blocks.CharBlock())]))], use_json_field=True),
        ),
    ]
