# Generated by Django 4.1.10 on 2023-08-27 21:19

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_anothertestinforme_buroku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anothertestinforme',
            name='buroku',
            field=wagtail.fields.StreamField([('parametros', wagtail.blocks.StructBlock([('year', wagtail.blocks.CharBlock()), ('molde', wagtail.blocks.StructBlock([('material', wagtail.blocks.CharBlock()), ('valor', wagtail.blocks.CharBlock()), ('porcentaje', wagtail.blocks.CharBlock())]))]))], use_json_field=True),
        ),
    ]
