# Generated by Django 4.1.10 on 2023-08-28 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_anothertestinforme_buroku'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnotherTestInforme',
        ),
    ]
