# Generated by Django 4.1.10 on 2023-08-28 04:26

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_anothertestinforme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anothertestinforme',
            name='buroku',
            field=wagtail.fields.StreamField([('id_year', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock()), ('year', wagtail.blocks.CharBlock())])), ('parametros', wagtail.blocks.StructBlock([('material', wagtail.blocks.CharBlock()), ('valor', wagtail.blocks.CharBlock()), ('porcentaje', wagtail.blocks.CharBlock())]))], use_json_field=True),
        ),
    ]
