# Generated by Django 4.1.10 on 2023-08-29 18:32

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_anothertestinforme_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anothertestinforme',
            name='description',
        ),
        migrations.AddField(
            model_name='anothertestinforme',
            name='protocolo',
            field=wagtail.fields.StreamField([('molde', wagtail.blocks.StructBlock([('description', wagtail.blocks.CharBlock()), ('material', wagtail.blocks.CharBlock()), ('topico', wagtail.blocks.CharBlock()), ('relevancia', wagtail.blocks.CharBlock()), ('fuentes', wagtail.blocks.CharBlock())]))], default=1, use_json_field=True),
            preserve_default=False,
        ),
    ]
