# Generated by Django 4.1.10 on 2023-08-29 18:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0052_remove_anothertestinforme_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherInforme',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tema_material', models.CharField(default='', max_length=140)),
                ('id_indicador', models.CharField(max_length=140)),
                ('medida', models.CharField(max_length=140)),
                ('responsable', models.CharField(max_length=140)),
                ('comentario', models.CharField(blank=True, max_length=500)),
                ('estado', models.CharField(max_length=140)),
                ('categoria', models.CharField(max_length=140)),
                ('buroku', wagtail.fields.StreamField([('id_year', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock()), ('year', wagtail.blocks.CharBlock())])), ('parameters', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock()), ('material', wagtail.blocks.CharBlock()), ('valor', wagtail.blocks.CharBlock()), ('porcentaje', wagtail.blocks.CharBlock())]))], use_json_field=True)),
                ('protocolo', wagtail.fields.StreamField([('molde', wagtail.blocks.StructBlock([('desc', wagtail.blocks.CharBlock()), ('mater', wagtail.blocks.CharBlock()), ('topic', wagtail.blocks.CharBlock()), ('relev', wagtail.blocks.CharBlock()), ('sources', wagtail.blocks.CharBlock())]))], use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='AnotherTestInforme',
        ),
    ]
